### ISSUE TITLE
Douban support implement

### ISSUE THREAD

**Issue by ericvlog** [yortem/chrome-stremio-imdb#4]
hello, bro just asking is possible add support on douban "https://movie.douban.com/"

It largest movie internet database in China.

Every or most movies pages have imdb link on it, 

https://movie.douban.com/subject/26957900

![ggg](https://github.com/user-attachments/assets/6630b48b-58c1-4072-8eb2-b5e9885ffd89)

Thanks for wonderful userscript. !!

**Comment by yortem** [comment]
Added. try version 1.0.9
![ביאור 2024-08-04 180222](https://github.com/user-attachments/assets/b9a564dc-41ef-449c-8adb-befa769d8609)
