### ISSUE TITLE
Not working well on themoviedb.org

### ISSUE THREAD

**Issue by FSA1** [yortem/chrome-stremio-imdb#5]
The Stremio button remains inactive for most titles on TMDB.

**Comment by yortem** [comment]
Can you send a title that doesn't work for example?

**Comment by FSA1** [comment]
Here's an example where the button appears inactive for me:
 https://www.themoviedb.org/movie/1022789-inside-out-2

By the way, I'm using the Chrome browser.

**Comment by yortem** [comment]
For me Inside Out 2 works well, but Fly Me To The Moon didn't. (maybe it's a matter of cache difference)

Anyway, I made an improvement for TMDB in case it doesn't find the movie using the Cinemeta database, so it will open the movie using the TMDb database. 
it means that you will need to have the TMDB addon on your Stremio for it to work. (as a backup to Cinemeta). 
I feel like the TMDB metadata addon is a basic addon anyone should have anyway, so it's not a problem.

Try the latest version 1.2.2 and tell me if it's working for you.

**Comment by FSA1** [comment]
Yes I have Cinemeta and TMDB installed on Stremio, I will test the latest version of the extension to see if it works, thanks

**Comment by FSA1** [comment]
I tested version 1.2.2 and it seems to work great now. Thanks again.

**Comment by yortem** [comment]
No problem
