### ISSUE TITLE
[FEATURE REQUEST] allow a different csv format for downloading imdb lists

### ISSUE THREAD

**Issue by hcgiub001** [yortem/chrome-stremio-imdb#9]
Hey thanks for this awesome extension!
I'm actually from the KODI scene and never dealt with stremio, we rely on TRAKT for our lists most of the time as they are integrated to addons.
I made a guide on how to use IMDB advance search lists and get them into TRAKT

https://www.reddit.com/r/Addons4Kodi/comments/1gikss1/guide_how_to_use_imdb_advanced_title_search_to/

right now I have to go into inspect, console, type in code, copy and paste that code into IMDB using a different extension then wait like minutes so it can load into IMDB then export...

It's very lengthy and when I saw how instant your csv list downloaded I got so excited. Once I get a CSV file I use traktrater 
https://github.com/damienhaynes/TraktRater

I tried your CSV file for a list I made but TraktRater needs it in the actual IMDB csv format.
I was hoping you would consider having an option to download the csv file to match the one IMDB gives
not sure if it's even possible

this is a csv that I got from IMDB export
[title_type=feature&genres=horror&keywords=vampire,vampire-hunter,independent-film.csv](https://github.com/user-attachments/files/17611794/title_type.feature.genres.horror.keywords.vampire.vampire-hunter.independent-film.csv)

Like Traktrater accepts

Position,Const,Created,Modified,Description,Title,Original Title,URL,Title Type,IMDb Rating,Runtime (mins),Year,Genres,Num Votes,Release Date,Directors,Your Rating,Date Rated
1,tt3416742,2024-11-03,2024-11-03,,"What We Do in the Shadows","What We Do in the Shadows",https://www.imdb.com/title/tt3416742/,Movie,7.6,86,2014,"Comedy, Horror",204476,2014-11-21,"Jemaine Clement, Taika Waititi",,

and your extension gives
Const,Title,Year,Rating
"tt0862856","Trick 'r Treat","2007","6.7"

I modified your csv output as

Position,Const,Created,Modified,Description,Title,Original Title,URL,Title Type,IMDb Rating,Runtime (mins),Year,Genres,Num Votes,Release Date,Directors,Your Rating,Date Rated
1,tt0862856,,,,"Trick 'r Treat",,,,6.7,,2007,,,,,

and traktrater accepts it, I was wondering if you could somehow have an option that you let users have it in this format. I want everyone to be able to easily create trakt lists so one less thing to worry about would be awesome.
Thanks for your consideration and let me know if you need any further information thanks

**Comment by yortem** [comment]
So basically you want the same rows as an exported list, but with empty values?

**Comment by hcgiub001** [comment]
hey thanks for such a fast response.
yes, this actually worked, also the top line needs to change like I've shown

Position,Const,Created,Modified,Description,Title,Original Title,URL,Title Type,IMDb Rating,Runtime (mins),Year,Genres,Num Votes,Release Date,Directors,Your Rating,Date Rated

but your year and rating is swapped.

This would be the a small change for you but their is something I really wanted to ask if you could implement that would be used so much in the KODI community 

I need to rely on traktrater to import into trakt. if your extension did this function that would be out of this world!
The api to import to trakt is very good I believe. instead of downloading a csv file, do you think you could add a button that instantly adds the list to trakt? 
you'll have to have your app approved, but even if you don't have the time or motivation just allowing to download in the CSV format that Traktrater needs would be so amazing!

Do you know if you can add more fields that traktrater wants? to make sure it finds the right file?

Thanks for any help

**Comment by yortem** [comment]
Can you try version 1.2.5?

**Comment by hcgiub001** [comment]
omg that was so fast, of course I will love to try, thanks for this. I'll report back!

**Comment by yortem** [comment]
okay, no problem. as for your request to make a tool directly to Trakt, I didn't research it yet, but I feel like it will be too much effort for little demand and considering there are tools that do things like this, it's worth even less. it's also not as pleasant to make tools for things I don't use.  but thank you for feedback.

Let me know if the extension works as expected now. I can't test on traktrater, so I don't know if there are more things that are needed, not only titles.

**Comment by hcgiub001** [comment]
completely understand, I would have said the same thing. 
I downloaded 1.2.5

it was perfect! worked like a charm for movies and I got so excited, but needed to test for tv shows
but it didn't work
this is csv from your addon
[Advanced title search (2).csv](https://github.com/user-attachments/files/17612060/Advanced.title.search.2.csv)

this is from importing into IMDB and getting an actual csv file from IMDB
[test003.csv](https://github.com/user-attachments/files/17612063/test003.csv)

this is the error log from traktrater
[20241103_090041.log](https://github.com/user-attachments/files/17612079/20241103_090041.log)


> 2024-11-03 21:00:41.412 [ERR ] [][44]: Error reading row 'CsvHelper.TypeConversion.TypeConverterException: The conversion cannot be performed.
>     Text: '2013–2023'
>     MemberName: Year
>     MemberType: System.Nullable`1[[System.Int32, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]]
>     TypeConverter: 'CsvHelper.TypeConversion.NullableConverter'
> IReader state:
>    ColumnCount: 18
>    CurrentIndex: 11
>    HeaderRecord:
> ["Position","Const","Created","Modified","Description","Title","Original Title","URL","Title Type","IMDb Rating","Runtime (mins)","Year","Genres","Num Votes","Release Date","Directors","Your Rating","Date Rated"]
> IParser state:
>    ByteCount: 0
>    CharCount: 265
>    Row: 2
>    RawRow: 2
>    Count: 18
>    RawRecord:
> "","tt2560140","","","","Attack on Titan","","","","9.1","","2013–2023","","","","","",""
> 

If you have some time available would love if you could figure this out. It's not a rush but honestly this tool is amazing! It's so fast and traktrater does the rest. thanks so much for looking into this. let me know if you need me to test more

**Comment by yortem** [comment]
I will check it tomorrow

**Comment by hcgiub001** [comment]
whenever you are free is fine , thanks again

**Comment by hcgiub001** [comment]
> I will check it tomorrow

I think I got it, for movies you are using year, 
and in series your programme picks up the start and end part of the year 

"","tt2560140","","","","Attack on Titan","","","","9.1","","2013–2023","","","","","",""

whereas IMDB is showing this
1,tt2560140,2024-11-03,2024-11-03,,"Attack on Titan","Shingeki no Kyojin",https://www.imdb.com/title/tt2560140/,TV Series,9.1,24,2013,"Animation, Action, Adventure, Drama, Fantasy, Horror",556800,2014-09-14,,,

maybe it just uses the beginning year? and cuts of the other part?

anyway will let you take a look when you have time thanks

**Comment by hcgiub001** [comment]
I'm wondering would it be better to literally just have the IMDB id and leave everything else blank?
wouldn't TMDB be able to figure out the show with that, it's a very unique identifier and anything else is superfluous? I'm not a dev so I'm not sure, but I know once you programme that it only takes the date and takes out the two elements - and the other date (if these are their) then we should be good.
you don't know how much time and effort this saves! it's saving me like 90% of the time It took before and now it's a few clicks!

**Comment by yortem** [comment]
Try version 1.2.51.

I need the other parts. I don't know what TMDB has anything to do with it. The extension was made mostly to be used with this tool I made https://www.journey.co.il/stremio/ and it loads the movies faster that way when there's an existing data instead of searching for other details in the database \ API.

**Comment by hcgiub001** [comment]
Sorry when I said TMDB I meant Trakt

For movies it's working perfectly. for series it's picking the shows but not all of them and it seems the information isn't enough to identify the correct show which confuses me since I thought the IMDB ID would be sufficient

I created a TV series list here
[Advanced title search (16).csv](https://github.com/user-attachments/files/17615122/Advanced.title.search.16.csv)

it picked up 21/50 
https://trakt.tv/users/addlistentry/lists/advanced-title-search-16?sort=rank,asc

![image](https://github.com/user-attachments/assets/8b554edf-9f8a-41ab-a7bf-61dc02a02d0b)

I then checked with the method I was using 

> right click on the page and select 'Inspect'
> 
> pick Console
> 

> 
> list = new Set()
> 
> document.querySelectorAll('.ipc-metadata-list-summary-item').forEach(i => {
> 
> var title = i.querySelector('.ipc-title-link-wrapper')
> 
> title = title.href.split('/')[4]
> 
> list.add(title)
> 
> })
> 
> console.log(new Array(...list).join('\n'))

> press enter, it will ask you to type something else and press enter so we can type in codes, do that then paste the code again and press enter

and create an IMDB list then export that list and use in Traktrater

I got this
[test544.csv](https://github.com/user-attachments/files/17615174/test544.csv)
it got 49/50

![image](https://github.com/user-attachments/assets/dff3ee85-51d8-4b58-91e8-21f5618ea537)
https://trakt.tv/users/addlistentry/lists/test544?sort=rank,asc

and if you have a look at "the old man" and compare, it wasn't able to pick the right show.

I'm curious do you have access to all the information that is used by IMDB to create an official csv export file, so basically do a carbon copy? I'm not sure if you do, otherwise I don't think we have enough information to get all the shows recognised and the ones it gets it's not getting the right show 100% of the time.

so right now you can get this

Position,Const,Created,Modified,Description,Title,Original Title,URL,Title Type,IMDb Rating,Runtime (mins),Year,Genres,Num Votes,Release Date,Directors,Your Rating,Date Rated
"","tt0944947","","","","Game of Thrones","","","","9.2","","2011","","","","","",""

but what would work perfectly if you can get this data

Position,Const,Created,Modified,Description,Title,Original Title,URL,Title Type,IMDb Rating,Runtime (mins),Year,Genres,Num Votes,Release Date,Directors,Your Rating,Date Rated
1,tt0944947,2024-11-04,2024-11-04,,"Game of Thrones","Game of Thrones",https://www.imdb.com/title/tt0944947/,TV Series,9.2,60,2011,"Action, Adventure, Drama, Fantasy",2360444,

If you don't I appreciate you doing this, for movie it seems to work well, just TV shows can be hit or miss.

**Comment by hcgiub001** [comment]
I've noticed the trakt list entries are all movies when I wanted series, since chrome-stremio-imdb doesn't list either movie or show, it's picking movies even though it has the IMDB ID, strange.

**Comment by yortem** [comment]
I don't know why trakt do things, my chrome extension wasn't meant for this use so I will not start to support this method. maybe they need more information that is not available when I scrap the page and for the current use, there's no need for that. 

I don't have access to the whole IMDB information, only what is visible on the page.

**Comment by hcgiub001** [comment]
> I don't know why trakt do things, my chrome extension wasn't meant for this use so I will not start to support this method. maybe they need more information that is not available when I scrap the page and for the current use, there's no need for that.
> 
> I don't have access to the whole IMDB information, only what is visible on the page.

I found the solution if you can add the type it would work

right now you have this

Position,Const,Created,Modified,Description,Title,Original Title,URL,Title Type,IMDb Rating,Runtime (mins),Year,Genres,Num Votes,Release Date,Directors,Your Rating,Date Rated
"","tt0944947","","","","Game of Thrones","","","","9.2","","2011","","","","","",""

We just need the Title Type, so the actual information is

"","tt0944947","","","","Game of Thrones","","","TV Series","9.2","","2011","","","","","",""

the title type is used in the IMDB advance search filters 

![image](https://github.com/user-attachments/assets/8237bd21-a9f9-426e-b47d-d76d836122d0)

do you have access to what the Title Type for each item is in the list?

worked perfectly when I added that information

**Comment by yortem** [comment]
Version 1.2.52 - If you filter TV Series (as it shows in your picture) it will give **all of them** TV Series in the column, if not, it's a movie. I won't go deeper than that since it's not necessary for the common use of Stremio users who use the other tool.

**Comment by hcgiub001** [comment]
this works perfectly for Movies, TV shows! I really do appreciate your time and effort.
I only ask one more thing so this can really benefit anyone who wants to use the IMDB advance search feature list into a trakt list. I'm sure their is a need and your great extension is just missing one piece.

Right now as it stands we can only add Movies or TV Shows. I'd like to add all the Title Types
-Movie
-TV Series
-Short
-TV Episode
-TV Mini Series
-TV Movie
-TV Special
-TV Short

If a user clicked Movie & TV Series then we'll get an error and if they pick short we'll get an error since it will label them as movie.

It would be a waste if their is a solution to find what the Title Type and label it accordingly (if one exists)
then people can't use your extension to the fullest in my community and others who want this feature. I'm sure their are many.

Would you be able to when you are free to see if that information is provided and label each item it's Title Type? time isn't an issue so when you are free.

after I would make a post and credit you, just like I made a post before and credited BONAFIDE BOSS for his code that allowed me to do the method I was using.

You extension is awesome and the KODI community also use Stremio
https://www.reddit.com/r/Addons4Kodi/comments/1b32a2i/stremio_vs_kodi/

I'm certain they would use this for both it's intended purpose to support Stremio users and it's extended purpose to support KODI community

Would you consider it?
If you don't have time I thank you again for all the work you've done, the tool as it is can still be used just not to it's full potential. :)

**Comment by yortem** [comment]
I don't think so. right now it works fine for the purpose that it has. Stremio doesn't have more than Movies \ TV Shows, everything else fits into one of those options in the Stremio app, so I don't think I will bother to dig more into it. use it for movies and shows, that's good enough.

**Comment by hcgiub001** [comment]
it's a great tool and again thanks for doing this. In fact one of the addon I use only allows you to search for movies (another has mixed) so for that alone this is great! You're a star thanks

**Comment by hcgiub001** [comment]
Please forgive me, I just wanted to ask you

I'm not a software engineer, I just wanted to see if I can find out what each item is using inspect element, and if I did to maybe ask again if you could make use of it :)

I found it I think
![image](https://github.com/user-attachments/assets/edd92ead-f587-45bb-abdc-5863f96a79d8)

next to each item is the Title tpye
![image](https://github.com/user-attachments/assets/50c2a2cd-6111-41c4-98d2-eeff3886df57)

I've highlighted it. not sure how your code works but would you be able to just add that as the Title type in the csv file for each entry, honestly I would be so grateful and you're script bridges IMDB and TRAKT like nothing before. would really just complete the script :)

**Comment by yortem** [comment]
I know that this thing exists, but as I said, it's not what this chrome extension for. I don't want to bother much for something that this wasn't the purpose for it and it might just cause more issues in the future or I will also need to support that when other problems will show up. I prefer not to get into this at all.

**Comment by hcgiub001** [comment]
perfectly understand, could you if it's not to much trouble scrape this and allow me to have it. I will not share with anyone and use it for my own personal use. The other method exists for users that want it, this I will use myself and if IMDB change the site and the extension stops working, I'd be fine and use the previous method, if it's not to much effort?

**Comment by yortem** [comment]
Try version 1.2.53

**Comment by hcgiub001** [comment]
yay! it's working almost perfectly! I just found one issue but every Title Type I've tried , even mixed ones work!
here is the issue

this is a search for short
![image](https://github.com/user-attachments/assets/49846b55-3a0c-43ed-a12e-05a1fc53adf6)

this is part of the csv file that chrome-stremio-imdb creates

"","tt32034208","","","","Batman Beyond: Year One","","","Movie","","","14m","","","","","",""

and this is what we are looking at (the bottom entry)
![image](https://github.com/user-attachments/assets/4ecf7bf4-a994-4f94-bdaf-d8bb86847907)

you see normal entries have this kind of data before the Title type label

> 2015 27m TV-MA
> 6.1 (2.9K) star

this is affecting the scrape of the label we want, so for some reason it's picking up the first entry in those cluster of labels, "14m" for the date
this brings up an error in Traktrater and won't create any list

this is the list I created
https://www.imdb.com/search/title/?title_type=short&genres=action

here is the same query but I'm searching for TV-Mini series instead

![image](https://github.com/user-attachments/assets/c40cd89d-55cd-4e50-98e6-e8e623d44a26)
(the query is https://www.imdb.com/search/title/?title_type=tv_miniseries&genres=action)

and this is the entry 
"","tt18224594","","","","Blade Runner 2099","","","TV Mini Series","","","TV-MA","","","","","",""


when some data is missing and the structure is different, chrome-stremio-imdb just grabs the wrong label, it should be looking for date but their is no date so it uses what is on that line, this is the only thing making this insanely amazing! do you think you can account for these instances? everything else is perfect!

**Comment by yortem** [comment]
So when this happens, remove the line manually. this doesn't impact the purpose of this extension, and as you see, it's endless... just use it as it is.

**Comment by hcgiub001** [comment]
sorry I got confused, with Title Type, so basically when i's looking for date on second line and if none exists, it will take whatever element is on the second line for the data

in my first example it took "14m"

In my second it took "TV-MA"

if you could leave it as blank it works I tried. Not sure what the best and most efficient method is for this.

Just out of curiosity, this would also have affected your own stremio addon, correct? does your application that makes use of this csv file disregard items it can't find? maybe this incorrect labelling of date is throwing away items that could be added it you removed the date for items that don't have one?
thanks for your work

**Comment by hcgiub001** [comment]
> So when this happens, remove the line manually. this doesn't impact the purpose of this extension, and as you see, it's endless... just use it as it is.

I know I'm asking for much, you've already done so much, just having this will fix everything.
you could have an if statement that if it's not in the format of 4 numbers then to not have a date for that element. after this whatever else is comes up I'll do it manually. it's just if I have a list of 1000 entries It would be challenging to find and correct the item so it works.

please could you just do this one last thing and it would be perfect since I've tested thoroughly and its amazing what you have created

**Comment by yortem** [comment]
1.2.54

**Comment by hcgiub001** [comment]
You're a legend! it works absolutely perfectly. I was testing it and most of my test I wasn't comparing to what IMDB would bring, once I did it's perfect 1:1! it really is amazing and I love it and your work! Thank you so much! I will not share with anyone and any issues I experience from now on I'll just try my best to get through them, I won't be asking for any issue request. If I use this for a month and everything is okay can I come back and ask your permission to share? I'll respect your wishes, it's just I would make it clear, no support will be provided for, though unless IMDB change their site, this won't be an issue.

Just out of curiosity , stremio uses Real-debrid just like KODI does, and some of these short movies I've had success finding a link, has your community not thought of adding short movies? you can add this as a section in your awesome site https://www.journey.co.il/stremio/

anyway You're a legend, if their is anything I can help with my ID on reddit is [pwreit2022](https://www.reddit.com/user/pwreit2022/) Thanks for this, really is an amazing extension and you don't realise what this opens up :) all the best.

**Comment by yortem** [comment]
It's already public so it's an official version anyone can use and share. glad I could help.
